apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: crowdscreen
spec:
  rules:
    - host: crowdscreen.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: { service: { name: app-svc, port: { number: 80 } } }
