apiVersion: apps/v1
kind: StatefulSet
metadata: { name: mongo, namespace: crowdscreen }
spec:
  serviceName: "mongo"
  replicas: 1
  selector: { matchLabels: { app: mongo } }
  template:
    metadata: { labels: { app: mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports: [{ containerPort: 27017 }]
          volumeMounts: [{ name: data, mountPath: /data/db }]
  volumeClaimTemplates:
    - metadata: { name: data }
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources: { requests: { storage: 5Gi } }
