apiVersion: v1
kind: Secret
metadata: { name: app-secrets, namespace: crowdscreen }
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYjovL21vbmdvOjI3MDE3L2Nyb3dkc2NyZWVu
  JWT_SECRET: ZGV2LXN1cGVyLXNlY3JldA==
